#!/bin/bash
git checkout master && cabal run build && cp .rsyncignore _site/ && git checkout gh-pages && rsync -av --delete --exclude-from=.rsyncignore _site/ ./ && git add --all && git commit -m 'Update site' && git push origin gh-pages
git checkout master
cabal run clean
