#!/bin/bash
cp .rsyncignore _site/ && cabal run build && git checkout gh-pages && rsync -av --delete --exclude-from=.rsyncignore _site/ ./ && git add --all && git commit -m 'Update site' && git push origin gh-pages
git checkout master
cabal run clean
